---
version: '3.7'

services:
  rprotobuf:
    build:
      context: .
    image: rprotobuf:0.0.1
    volumes:
      - type: bind
        source: .
        target: /go/src/github.com/ronaldoafonso/rprotobuf
    command: ["/bin/sh", "-c", "while :; do sleep 10; done"]
...
